import { IsDateString, IsEnum, IsNumber, IsOptional, IsString, IsUUID, Min, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';
import { RestaurantInventoryUnitType, RestaurantShift, RestaurantStockPolicy } from '@prisma/client';

export class CreateCategoryDto { @IsString() name!: string; @IsOptional() @IsString() description?: string; }
export class CreateUnitDto { @IsString() name!: string; @IsString() abbreviation!: string; @IsEnum(RestaurantInventoryUnitType) type!: RestaurantInventoryUnitType; @IsOptional() @IsUUID() baseUnitId?: string; @IsNumber() @Min(0) conversionFactor!: number; @IsOptional() @IsNumber() decimalPrecision?: number; }
export class CreateWarehouseDto { @IsUUID() branchId!: string; @IsString() name!: string; @IsString() code!: string; }
export class CreateSupplierDto { @IsString() name!: string; @IsOptional() @IsString() contactName?: string; @IsOptional() @IsString() email?: string; @IsOptional() @IsString() phone?: string; @IsOptional() @IsString() address?: string; @IsOptional() @IsString() taxId?: string; }
export class CreateIngredientDto { @IsOptional() @IsUUID() categoryId?: string; @IsString() sku!: string; @IsString() name!: string; @IsOptional() @IsString() description?: string; @IsUUID() inventoryUnitId!: string; @IsUUID() purchaseUnitId!: string; @IsNumber() @Min(0) purchaseConversionFactor!: number; @IsOptional() @IsNumber() @Min(0) minimumStock?: number; }
export class ReceiptItemDto { @IsUUID() ingredientId!: string; @IsNumber() @Min(0.000001) purchaseQuantity!: number; @IsUUID() purchaseUnitId!: string; @IsNumber() @Min(0) conversionFactor!: number; @IsNumber() @Min(0) unitCost!: number; @IsOptional() @IsString() lotNumber?: string; @IsOptional() @IsDateString() expirationDate?: string; }
export class CreateReceiptDto { @IsUUID() branchId!: string; @IsUUID() warehouseId!: string; @IsOptional() @IsUUID() supplierId?: string; @IsOptional() @IsString() supplierInvoiceNumber?: string; @IsDateString() receivedAt!: string; @IsOptional() @IsString() notes?: string; @ValidateNested({ each: true }) @Type(() => ReceiptItemDto) items!: ReceiptItemDto[]; }
export class RecipeItemDto { @IsUUID() ingredientId!: string; @IsNumber() @Min(0.000001) quantity!: number; @IsUUID() unitId!: string; @IsOptional() @IsNumber() @Min(0) wastePercentage?: number; @IsOptional() @IsNumber() position?: number; }
export class CreateRecipeDto { @IsOptional() @IsUUID() branchId?: string; @IsString() code!: string; @IsString() name!: string; @IsOptional() @IsString() description?: string; @IsOptional() @IsUUID() categoryId?: string; @IsOptional() @IsUUID() outputIngredientId?: string; @IsNumber() @Min(0.000001) yieldQuantity!: number; @IsUUID() yieldUnitId!: string; @IsOptional() @IsNumber() sellingPrice?: number; @IsOptional() @IsEnum(RestaurantStockPolicy) requiredStockPolicy?: RestaurantStockPolicy; @ValidateNested({ each: true }) @Type(() => RecipeItemDto) items!: RecipeItemDto[]; }
export class ConsumptionItemDto { @IsUUID() recipeId!: string; @IsNumber() @Min(0.000001) quantitySold!: number; }
export class CreateConsumptionDto { @IsUUID() branchId!: string; @IsUUID() warehouseId!: string; @IsDateString() consumptionDate!: string; @IsEnum(RestaurantShift) shift!: RestaurantShift; @IsOptional() @IsString() notes?: string; @ValidateNested({ each: true }) @Type(() => ConsumptionItemDto) items!: ConsumptionItemDto[]; }
export class WasteItemDto { @IsUUID() ingredientId!: string; @IsNumber() @Min(0.000001) quantity!: number; @IsUUID() unitId!: string; @IsOptional() @IsString() notes?: string; }
export class CreateWasteDto { @IsUUID() branchId!: string; @IsUUID() warehouseId!: string; @IsDateString() wasteDate!: string; @IsString() reason!: string; @ValidateNested({ each: true }) @Type(() => WasteItemDto) items!: WasteItemDto[]; }

export class CreateProductionDto { @IsUUID() branchId!: string; @IsUUID() warehouseId!: string; @IsUUID() recipeId!: string; @IsNumber() @Min(0.000001) plannedQuantity!: number; @IsNumber() @Min(0.000001) actualYield!: number; @IsDateString() productionDate!: string; }
export class CountItemDto { @IsUUID() ingredientId!: string; @IsNumber() @Min(0) countedQuantity!: number; @IsOptional() @IsString() reason?: string; @IsOptional() @IsString() notes?: string; }
export class CreateStockCountDto { @IsUUID() branchId!: string; @IsUUID() warehouseId!: string; @IsDateString() countedAt!: string; @ValidateNested({ each: true }) @Type(() => CountItemDto) items!: CountItemDto[]; }
export class TransferItemDto { @IsUUID() ingredientId!: string; @IsOptional() @IsUUID() lotId?: string; @IsNumber() @Min(0.000001) quantity!: number; }
export class CreateTransferDto { @IsUUID() sourceBranchId!: string; @IsUUID() sourceWarehouseId!: string; @IsUUID() destinationBranchId!: string; @IsUUID() destinationWarehouseId!: string; @ValidateNested({ each: true }) @Type(() => TransferItemDto) items!: TransferItemDto[]; }
