export enum ErrorCode {
  TENANT_CONTEXT_REQUIRED = 'TENANT_CONTEXT_REQUIRED',
  BRANCH_CONTEXT_REQUIRED = 'BRANCH_CONTEXT_REQUIRED',
  FORBIDDEN_BRANCH_SCOPE = 'FORBIDDEN_BRANCH_SCOPE',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
}
