import { Body, Controller, Get, Headers, Param, Post, Query, Req, UseGuards } from '@nestjs/common';
import { ModuleCode } from '@prisma/client';
import { RequireModule } from '../common/decorators/module-access.decorator';
import { RequirePermissions } from '../common/decorators/permissions.decorator';
import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';
import { ModuleAccessGuard } from '../common/guards/module-access.guard';
import { PermissionGuard } from '../common/guards/permission.guard';
import { ScopeGuard } from '../common/guards/scope.guard';
import { SubscriptionGuard } from '../common/guards/subscription.guard';
import { TenantGuard } from '../common/guards/tenant.guard';
import { RequestWithUser } from '../common/types/request-with-user.type';
import { CreateProductivityDemoEventDto, ListProductivityEventsQueryDto } from './dto/productivity-event.dto';
import { ProductivityService } from './productivity.service';
import { Public } from '../common/decorators/public.decorator';
@Controller('productivity') @UseGuards(JwtAuthGuard,TenantGuard,SubscriptionGuard,ModuleAccessGuard,ScopeGuard,PermissionGuard) @RequireModule(ModuleCode.AI_PRODUCTIVITY)
export class ProductivityController { constructor(private readonly service: ProductivityService) {} @Get('insights') @RequirePermissions('productivity.view') insights(@Req() r:RequestWithUser,@Query('branchId') b?:string){return this.service.insights(r.tenant!.id,b)} @Get('overview') @RequirePermissions('productivity.view') overview(@Req() r:RequestWithUser,@Query('branchId') b?:string){return this.service.overview(r.tenant!.id,b)} @Get('events') @RequirePermissions('productivity.view') events(@Req() r:RequestWithUser,@Query() q:ListProductivityEventsQueryDto){return this.service.events(r.tenant!.id,q)} @Post('events/demo') @RequirePermissions('productivity.manage') demoEvent(@Req() r:RequestWithUser,@Body() b:CreateProductivityDemoEventDto){r.auditAction='PRODUCTIVITY_DEMO_EVENT_CREATED';return this.service.createDemoEvent(r.tenant!.id,b)} @Get('cameras') @RequirePermissions('productivity.view') cameras(@Req() r:RequestWithUser,@Query('branchId') b?:string){return this.service.cameras(r.tenant!.id,b)} @Post('cameras') @RequirePermissions('productivity.manage') camera(@Req() r:RequestWithUser,@Body() b:never){r.auditAction='PRODUCTIVITY_CAMERA_CREATED';return this.service.createCamera(r.tenant!.id,b)} @Get('zones') @RequirePermissions('productivity.view') zones(@Req() r:RequestWithUser,@Query('cameraId') c?:string){return this.service.zones(r.tenant!.id,c)} @Post('zones') @RequirePermissions('productivity.manage') zone(@Req() r:RequestWithUser,@Body() b:never){r.auditAction='PRODUCTIVITY_ZONE_CREATED';return this.service.createZone(r.tenant!.id,b)} @Get('alert-rules') @RequirePermissions('productivity.manage') rules(@Req() r:RequestWithUser){return this.service.alertRules(r.tenant!.id)} @Post('alert-rules') @RequirePermissions('productivity.manage') rule(@Req() r:RequestWithUser,@Body() b:never){r.auditAction='PRODUCTIVITY_ALERT_RULE_CREATED';return this.service.createAlertRule(r.tenant!.id,b)} @Get('alerts') @RequirePermissions('productivity.view') alerts(@Req() r:RequestWithUser,@Query('branchId') b?:string){return this.service.alerts(r.tenant!.id,b)} @Post('alerts/:id/:status') @RequirePermissions('productivity.manage') alert(@Req() r:RequestWithUser,@Param('id') id:string,@Param('status') status:'ACKNOWLEDGED'|'CLOSED'){r.auditAction='PRODUCTIVITY_ALERT_UPDATED';return this.service.updateAlert(r.tenant!.id,id,status)} }
@Controller('internal/productivity')
@Public()
export class ProductivityInternalController { constructor(private readonly service: ProductivityService) {} @Post('events') ingest(@Headers('x-productivity-service-key') key:string|undefined,@Body() body:never){return this.service.ingest(key,body)} }
