import { Body, Controller, Get, Param, Patch, Post, Query, Req, UseGuards, UseInterceptors } from '@nestjs/common';
import { InventoryCapabilityCode, RestaurantCommissaryStatus } from '@prisma/client';
import { RequireInventoryCapability } from '../inventory-capabilities/inventory-capability.decorator';
import { InventoryCapabilityGuard } from '../inventory-capabilities/inventory-capability.guard';
import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';
import { TenantGuard } from '../common/guards/tenant.guard';
import { SubscriptionGuard } from '../common/guards/subscription.guard';
import { PermissionGuard } from '../common/guards/permission.guard';
import { RequirePermissions } from '../common/decorators/permissions.decorator';
import { RequestWithUser } from '../common/types/request-with-user.type';
import { RestaurantInventoryContextGuard } from './restaurant-inventory-context.guard';
import { RestaurantInventoryIdempotencyInterceptor } from './restaurant-inventory-idempotency.interceptor';
import { RestaurantCommercialService } from './restaurant-commercial.service';
import { CommercialQueryDto, CommissaryQueryDto, CreateCommercialBudgetDto, CreateCommissaryDto, UnitComparisonQueryDto, UpdateCommercialBudgetDto, UpdateCommissaryDto } from './dto/restaurant-inventory.dto';
import { AuditAction } from '../audit/audit-action.decorator';
import { RestaurantCommissaryService } from './restaurant-commissary.service';

@Controller('restaurant-inventory/commercial')
@UseGuards(JwtAuthGuard, TenantGuard, SubscriptionGuard, PermissionGuard, InventoryCapabilityGuard, RestaurantInventoryContextGuard)
@UseInterceptors(RestaurantInventoryIdempotencyInterceptor)
@RequireInventoryCapability(InventoryCapabilityCode.RESTAURANT_INVENTORY)
export class RestaurantCommercialController {
  constructor(private readonly commercial: RestaurantCommercialService, private readonly commissaries: RestaurantCommissaryService) {}
  @Get('demand-forecast') @RequirePermissions('restaurant_inventory.commercial.view') async demand(@Req() r: RequestWithUser, @Query() q: CommercialQueryDto) { const result: any = await this.commercial.demandForecast(r.tenant!.id, q); return result.rows.map((row: any) => ({ period: `${new Date(row.period.start).toISOString()}/${new Date(row.period.end).toISOString()}`, ingredientId: row.ingredient.id, ingredientName: row.ingredient.name, branchId: row.branch.id, predictedQuantity: row.forecastQuantity ?? 0, confidence: row.confidence, lowerBound: row.lowerBound ?? 0, upperBound: row.upperBound ?? 0, unit: row.unit?.abbreviation ?? row.unit?.name })); }
  @Get('branch-costs') @RequirePermissions('restaurant_inventory.commercial.view') async costs(@Req() r: RequestWithUser, @Query() q: CommercialQueryDto) { const result: any = await this.commercial.branchCosts(r.tenant!.id, q); return result.rows.map((row: any) => ({ branchId: row.branch.id, branchName: row.branch.name, period: `${new Date(row.period.start).toISOString()}/${new Date(row.period.end).toISOString()}`, inventoryCost: row.inventoryValue, purchaseCost: row.purchasesConfirmed, consumptionCost: row.consumptionCost, foodCostPercent: row.foodCostPercent, varianceCost: row.theoreticalRealVariance })); }
  @Get('recipe-margins') @RequirePermissions('restaurant_inventory.commercial.view') async margins(@Req() r: RequestWithUser, @Query() q: CommercialQueryDto) { const result: any = await this.commercial.recipeMargins(r.tenant!.id, q); return result.rows.map((row: any) => ({ recipeId: row.recipe.id, recipeName: row.recipe.name, period: `${new Date(row.period.start).toISOString()}/${new Date(row.period.end).toISOString()}`, portions: row.portionsSold, revenue: row.revenue, cost: row.totalCost, margin: row.margin, marginPercent: row.marginPercent ?? 0 })); }
  @Get('unit-comparison') @RequirePermissions('restaurant_inventory.commercial.view') async unitComparison(@Req() r: RequestWithUser, @Query() q: UnitComparisonQueryDto) { const result: any = await this.commercial.unitComparison(r.tenant!.id, q, r.user.allowedBranchIds, r.user.isGlobalContext); return result.rows.map((row: any) => ({ metric: row.metric, unit: row.unit?.name ?? row.unit?.id ?? row.unit, period: `${new Date(row.period.start).toISOString()}/${new Date(row.period.end).toISOString()}`, value: row.value ?? 0, rank: row.ranking, changePercent: row.changeVsPreviousPeriod })); }
  @Get('comparative') @RequirePermissions('restaurant_inventory.commercial.view') comparative(@Req() r: RequestWithUser, @Query() q: CommercialQueryDto) { return this.commercial.comparative(r.tenant!.id, q); }
  @Get('commissary') @RequirePermissions('restaurant_inventory.commissary.manage') commissary(@Req() r: RequestWithUser, @Query() q: CommercialQueryDto) { return this.commercial.commissary(r.tenant!.id, q); }
  @Get('commissaries') @RequirePermissions('restaurant_inventory.commissary.manage') async listCommissaries(@Req() r: RequestWithUser, @Query() q: CommissaryQueryDto) { const result: any = await this.commissaries.list(r.tenant!.id, q); return result.rows.map((row: any) => ({ id: row.id, code: row.code, name: row.name, status: row.status, branchCount: row.servedBranches.length, itemsCount: row.allowedIngredients.length + row.producedRecipes.length, updatedAt: row.updatedAt })); }
  @Post('commissaries') @RequirePermissions('restaurant_inventory.commissary.manage') @AuditAction('RESTAURANT_INVENTORY_COMMISSARY_CREATED') async createCommissary(@Req() r: RequestWithUser, @Body() dto: CreateCommissaryDto) { return this.commissaryDto(await this.commissaries.create(r.tenant!.id, r.user.sub, dto)); }
  @Patch('commissaries/:id') @RequirePermissions('restaurant_inventory.commissary.manage') @AuditAction('RESTAURANT_INVENTORY_COMMISSARY_UPDATED') async updateCommissary(@Req() r: RequestWithUser, @Param('id') id: string, @Body() dto: UpdateCommissaryDto) { return this.commissaryDto(await this.commissaries.update(r.tenant!.id, r.user.sub, id, dto)); }
  @Post('commissaries/:id/activate') @RequirePermissions('restaurant_inventory.commissary.manage') @AuditAction('RESTAURANT_INVENTORY_COMMISSARY_ACTIVATED') async activateCommissary(@Req() r: RequestWithUser, @Param('id') id: string) { return this.commissaryDto(await this.commissaries.transition(r.tenant!.id, r.user.sub, id, RestaurantCommissaryStatus.ACTIVE)); }
  @Post('commissaries/:id/deactivate') @RequirePermissions('restaurant_inventory.commissary.manage') @AuditAction('RESTAURANT_INVENTORY_COMMISSARY_DEACTIVATED') async deactivateCommissary(@Req() r: RequestWithUser, @Param('id') id: string) { return this.commissaryDto(await this.commissaries.transition(r.tenant!.id, r.user.sub, id, RestaurantCommissaryStatus.INACTIVE)); }
  @Get('budgets') @RequirePermissions('restaurant_inventory.budgets.manage') budgets(@Req() r: RequestWithUser, @Query() q: CommercialQueryDto & { status?: string }) { return this.commercial.budgets(r.tenant!.id, q); }
  @Post('budgets') @RequirePermissions('restaurant_inventory.budgets.manage') @AuditAction('RESTAURANT_INVENTORY_COMMERCIAL_BUDGET_CREATED') createBudget(@Req() r: RequestWithUser, @Body() dto: CreateCommercialBudgetDto) { return this.commercial.createBudget(r.tenant!.id, r.user.sub, dto); }
  @Patch('budgets/:id') @RequirePermissions('restaurant_inventory.budgets.manage') @AuditAction('RESTAURANT_INVENTORY_COMMERCIAL_BUDGET_UPDATED') updateBudget(@Req() r: RequestWithUser, @Param('id') id: string, @Body() dto: UpdateCommercialBudgetDto) { return this.commercial.updateBudget(r.tenant!.id, r.user.sub, id, dto); }
  @Get('purchase-budgets') @RequirePermissions('restaurant_inventory.budgets.manage') async purchaseBudgets(@Req() r: RequestWithUser, @Query() q: CommercialQueryDto & { status?: string; supplierId?: string; categoryId?: string }) { const result: any = await this.commercial.budgets(r.tenant!.id, q); return result.rows.map((row: any) => this.budgetDto(row)); }
  @Post('purchase-budgets') @RequirePermissions('restaurant_inventory.budgets.manage') @AuditAction('RESTAURANT_INVENTORY_PURCHASE_BUDGET_CREATED') async createPurchaseBudget(@Req() r: RequestWithUser, @Body() dto: CreateCommercialBudgetDto) { return this.budgetDto(await this.commercial.createBudget(r.tenant!.id, r.user.sub, this.normalizeBudget(dto, r))); }
  @Patch('purchase-budgets/:id') @RequirePermissions('restaurant_inventory.budgets.manage') @AuditAction('RESTAURANT_INVENTORY_PURCHASE_BUDGET_UPDATED') updatePurchaseBudget(@Req() r: RequestWithUser, @Param('id') id: string, @Body() dto: UpdateCommercialBudgetDto) { return this.commercial.updateBudget(r.tenant!.id, r.user.sub, id, dto); }
  @Post('purchase-budgets/:id/approve') @RequirePermissions('restaurant_inventory.budgets.manage') @AuditAction('RESTAURANT_INVENTORY_PURCHASE_BUDGET_APPROVED') async approvePurchaseBudget(@Req() r: RequestWithUser, @Param('id') id: string) { return this.budgetDto(await this.commercial.approveBudget(r.tenant!.id, r.user.sub, id)); }
  @Post('purchase-budgets/:id/close') @RequirePermissions('restaurant_inventory.budgets.manage') @AuditAction('RESTAURANT_INVENTORY_PURCHASE_BUDGET_CLOSED') async closePurchaseBudget(@Req() r: RequestWithUser, @Param('id') id: string) { return this.budgetDto(await this.commercial.closeBudget(r.tenant!.id, r.user.sub, id)); }
  private budgetDto(row: any) { return { id: row.id, period: `${new Date(row.periodStart).toISOString()}/${new Date(row.periodEnd).toISOString()}`, branchId: row.branchId, branchName: row.branchName, budget: Number(row.budgetAmount ?? 0), committed: Number(row.committedAmount ?? 0), received: Number(row.receivedAmount ?? 0), remaining: Number(row.remainingAmount ?? 0), utilizationPercent: Number(row.utilizationPercent ?? 0), status: row.status }; }
  private commissaryDto(row: any) { return { id: row.id, code: row.code, name: row.name, status: row.status, branchCount: row.servedBranches?.length ?? 0, itemsCount: (row.allowedIngredients?.length ?? 0) + (row.producedRecipes?.length ?? 0), updatedAt: row.updatedAt }; }
  private normalizeBudget(dto: CreateCommercialBudgetDto, request: RequestWithUser) { const period = dto.period ?? ''; const [year, month] = period.split('-').map(Number); const start = dto.periodStart ?? (year && month ? new Date(Date.UTC(year, month - 1, 1)).toISOString() : undefined); const end = dto.periodEnd ?? (year && month ? new Date(Date.UTC(year, month, 0, 23, 59, 59, 999)).toISOString() : undefined); const branchId = dto.branchId ?? request.user.activeBranchId ?? undefined; const code = dto.code ?? `BUD-${period}-${branchId?.slice(0, 8) ?? 'TENANT'}`; return { ...dto, branchId, code, periodStart: start, periodEnd: end, budgetAmount: dto.budgetAmount ?? dto.budget }; }
}
