import { HttpStatus, Inject, Injectable } from '@nestjs/common';
import { createHash } from 'crypto';
import { promises as fs } from 'fs';
import { join } from 'path';
import { PrismaService } from '../common/prisma/prisma.service';
import { AppException } from '../common/errors/app-exception';
import { ErrorCode } from '../common/errors/error-code.enum';

export interface OcrInvoiceLine { externalSku?: string; description?: string; quantity: number; unit?: string; unitCost: number; totalCost: number; }
export interface OcrInvoiceResult { supplierName?: string; invoiceNumber?: string; invoiceDate?: string; currency?: string; subtotal?: number; taxAmount?: number; totalAmount?: number; confidence: number; lines: OcrInvoiceLine[]; raw?: unknown; }
export interface InvoiceOcrProvider { process(document: Buffer): Promise<OcrInvoiceResult>; }
export const INVOICE_OCR_PROVIDER = 'INVOICE_OCR_PROVIDER';

@Injectable()
export class BasicInvoiceOcrProvider implements InvoiceOcrProvider {
  async process(_document: Buffer): Promise<OcrInvoiceResult> { return { confidence: 0, lines: [], raw: { provider: 'basic-review-required' } }; }
}

@Injectable()
export class RestaurantInvoiceService {
  constructor(private readonly prisma: PrismaService, @Inject(INVOICE_OCR_PROVIDER) private readonly ocr: InvoiceOcrProvider) {}
  private fail(message: string, code = ErrorCode.BAD_REQUEST, status = HttpStatus.BAD_REQUEST): never { throw new AppException(message, code, status); }
  private async context(tenantId: string, branchId: string, warehouseId: string) { const branch = await this.prisma.branch.findFirst({ where: { id: branchId, tenantId, inventoryStatus: 'ACTIVE' } }); if (!branch) this.fail('Sucursal inválida', ErrorCode.BRANCH_ACCESS_DENIED, HttpStatus.FORBIDDEN); const warehouse = await this.prisma.restaurantInventoryWarehouse.findFirst({ where: { id: warehouseId, tenantId, branchId, status: 'ACTIVE' } }); if (!warehouse) this.fail('Almacén inválido', ErrorCode.BRANCH_ACCESS_DENIED, HttpStatus.FORBIDDEN); }
  async upload(tenantId: string, userId: string, branchId: string, warehouseId: string, file: Express.Multer.File) { await this.context(tenantId, branchId, warehouseId); if (!file) this.fail('Archivo requerido'); const ext = file.originalname.toLowerCase().split('.').pop(); const allowed: Record<string, string[]> = { pdf: ['application/pdf'], jpg: ['image/jpeg'], jpeg: ['image/jpeg'], png: ['image/png'] }; if (!allowed[ext ?? '']?.includes(file.mimetype)) this.fail('Tipo de factura no permitido'); const validMagic = (ext === 'pdf' && file.buffer.subarray(0, 5).toString() === '%PDF-') || (['jpg', 'jpeg'].includes(ext ?? '') && file.buffer.subarray(0, 3).equals(Buffer.from([0xff, 0xd8, 0xff]))) || (ext === 'png' && file.buffer.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))); if (!validMagic) this.fail('Contenido de factura inválido'); const max = Number(process.env.INVOICE_MAX_UPLOAD_BYTES ?? 15 * 1024 * 1024); if (file.size > max) this.fail('La factura excede el tamaño máximo'); const hash = createHash('sha256').update(file.buffer).digest('hex'); const duplicate = await this.prisma.restaurantInvoice.findFirst({ where: { tenantId, fileHash: hash } }); if (duplicate) return duplicate; const baseDir = process.env.INVOICE_STORAGE_DIR ?? join('/tmp', 'restaurant-invoices'); const key = `${tenantId}/${hash}.${ext}`; await fs.mkdir(join(baseDir, tenantId), { recursive: true }); await fs.writeFile(join(baseDir, key), file.buffer, { flag: 'wx' }).catch((error: any) => { if (error?.code !== 'EEXIST') throw error; }); return this.prisma.restaurantInvoice.create({ data: { tenantId, branchId, warehouseId, fileName: file.originalname.replace(/[^a-zA-Z0-9._-]/g, '_'), fileHash: hash, fileStorageKey: key, createdBy: userId } }); }
  async list(tenantId: string, filters: any = {}) { return this.prisma.restaurantInvoice.findMany({ where: { tenantId, ...(filters.branchId ? { branchId: filters.branchId } : {}), ...(filters.warehouseId ? { warehouseId: filters.warehouseId } : {}), ...(filters.status ? { status: filters.status } : {}) }, include: { lines: true }, orderBy: { createdAt: 'desc' } }); }
  async get(tenantId: string, id: string) { const value = await this.prisma.restaurantInvoice.findFirst({ where: { id, tenantId }, include: { lines: true } }); if (!value) this.fail('Factura no encontrada', ErrorCode.RESOURCE_NOT_FOUND, HttpStatus.NOT_FOUND); return value; }
  async process(tenantId: string, userId: string, id: string) { const invoice: any = await this.get(tenantId, id); if (invoice.status === 'APPROVED') return invoice; if (!['UPLOADED', 'FAILED', 'REVIEW_REQUIRED'].includes(invoice.status)) this.fail('La factura no puede procesarse en su estado actual', ErrorCode.RESOURCE_CONFLICT, HttpStatus.CONFLICT); const baseDir = process.env.INVOICE_STORAGE_DIR ?? join('/tmp', 'restaurant-invoices'); const result = await this.ocr.process(await fs.readFile(join(baseDir, invoice.fileStorageKey))); return this.prisma.$transaction(async (tx) => tx.restaurantInvoice.update({ where: { id }, data: { supplierName: result.supplierName, invoiceNumber: result.invoiceNumber, invoiceDate: result.invoiceDate ? new Date(result.invoiceDate) : undefined, currency: result.currency ?? 'USD', subtotal: result.subtotal, taxAmount: result.taxAmount, totalAmount: result.totalAmount, confidence: result.confidence, status: result.confidence >= Number(process.env.INVOICE_OCR_MIN_CONFIDENCE ?? 0.8) ? 'REVIEW_REQUIRED' : 'REVIEW_REQUIRED', ocrPayload: result.raw, processedBy: userId, processedAt: new Date(), lines: { deleteMany: {}, create: result.lines.map((line) => ({ externalSku: line.externalSku, description: line.description, quantity: line.quantity, unit: line.unit, unitCost: line.unitCost, totalCost: line.totalCost })) } } as any, include: { lines: true } })); }
  async match(tenantId: string, userId: string, id: string, dto: any) { const invoice: any = await this.get(tenantId, id); if (!['PROCESSING', 'REVIEW_REQUIRED', 'MATCHED'].includes(invoice.status)) this.fail('La factura no está lista para conciliación', ErrorCode.RESOURCE_CONFLICT, HttpStatus.CONFLICT); const order: any = dto.purchaseOrderId ? await this.prisma.restaurantPurchaseOrder.findFirst({ where: { id: dto.purchaseOrderId, tenantId }, include: { lines: true } }) : null; if (dto.purchaseOrderId && !order) this.fail('Orden de compra no encontrada', ErrorCode.RESOURCE_NOT_FOUND, HttpStatus.NOT_FOUND); const differences: any[] = []; if (order && invoice.supplierId && invoice.supplierId !== order.supplierId) differences.push('SUPPLIER_MISMATCH'); if (order && invoice.totalAmount != null && Math.abs(Number(invoice.totalAmount) - Number(order.totalAmount)) > 0.01) differences.push('INVOICE_TOTAL_MISMATCH'); return this.prisma.restaurantInvoice.update({ where: { id }, data: { purchaseOrderId: dto.purchaseOrderId, receiptId: dto.receiptId, status: differences.length ? 'REVIEW_REQUIRED' : 'MATCHED', ocrPayload: { ...(invoice.ocrPayload as any ?? {}), reconciliation: { differences, matchedBy: userId, matchedAt: new Date().toISOString() } } }, include: { lines: true } }); }
  async approve(tenantId: string, userId: string, id: string) { const invoice: any = await this.get(tenantId, id); if (invoice.status !== 'MATCHED') this.fail('Solo se puede aprobar una factura conciliada', ErrorCode.RESOURCE_CONFLICT, HttpStatus.CONFLICT); if (Number(invoice.confidence ?? 0) < Number(process.env.INVOICE_OCR_MIN_CONFIDENCE ?? 0.8)) this.fail('La confianza OCR requiere revisión manual', ErrorCode.RESOURCE_CONFLICT, HttpStatus.CONFLICT); return this.prisma.restaurantInvoice.update({ where: { id }, data: { status: 'APPROVED', approvedBy: userId, approvedAt: new Date() }, include: { lines: true } }); }
  async reject(tenantId: string, userId: string, id: string, reason: string) { if (!reason?.trim()) this.fail('El motivo es obligatorio'); const invoice: any = await this.get(tenantId, id); if (invoice.status === 'APPROVED') this.fail('Una factura aprobada no puede rechazarse', ErrorCode.RESOURCE_CONFLICT, HttpStatus.CONFLICT); return this.prisma.restaurantInvoice.update({ where: { id }, data: { status: 'REJECTED', rejectedBy: userId, rejectedAt: new Date(), ocrPayload: { ...(invoice.ocrPayload as any ?? {}), rejectionReason: reason } } }); }
}
