import { Body, Controller, Delete, Get, Param, Patch, Post, Query, Req, UseGuards } from '@nestjs/common';
import { InventoryCapabilityCode } from '@prisma/client';
import { RequireInventoryCapability } from '../inventory-capabilities/inventory-capability.decorator';
import { InventoryCapabilityGuard } from '../inventory-capabilities/inventory-capability.guard';
import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';
import { TenantGuard } from '../common/guards/tenant.guard';
import { SubscriptionGuard } from '../common/guards/subscription.guard';
import { PermissionGuard } from '../common/guards/permission.guard';
import { RequirePermissions } from '../common/decorators/permissions.decorator';
import { RequestWithUser } from '../common/types/request-with-user.type';
import { RestaurantInventoryService } from './restaurant-inventory.service';
import { CreateCategoryDto, CreateConsumptionDto, CreateIngredientDto, CreateProductionDto, CreateReceiptDto, CreateRecipeDto, CreateStockCountDto, CreateSupplierDto, CreateTransferDto, CreateUnitDto, CreateWarehouseDto, CreateWasteDto, OverrideConfirmationDto, UpdateReceiptDto } from './dto/restaurant-inventory.dto';
import { RestaurantInventoryContextGuard } from './restaurant-inventory-context.guard';
import { AuditAction } from '../audit/audit-action.decorator';
import { CreateAdjustmentDto, CreateBranchDto, InventoryListQueryDto, UpdateBranchDto, UpdateCategoryDto, UpdateIngredientDto, UpdateSupplierDto, UpdateUnitDto, UpdateWarehouseDto } from './dto/restaurant-inventory.dto';

@Controller('restaurant-inventory')
@UseGuards(JwtAuthGuard, TenantGuard, SubscriptionGuard, PermissionGuard, InventoryCapabilityGuard, RestaurantInventoryContextGuard)
@RequireInventoryCapability(InventoryCapabilityCode.RESTAURANT_INVENTORY)
export class RestaurantInventoryController {
  constructor(private readonly service: RestaurantInventoryService) {}
  @Get('dashboard') @RequirePermissions('inventory.read') dashboard(@Req() r: RequestWithUser, @Query('branchId') branchId?: string, @Query('warehouseId') warehouseId?: string, @Query('from') from?: string, @Query('to') to?: string) { return this.service.dashboard(r.tenant!.id, { branchId, warehouseId, from, to }); }
  @Get('categories') @RequirePermissions('inventory.read') categories(@Req() r: RequestWithUser, @Query() q: InventoryListQueryDto) { return this.service.categories(r.tenant!.id, q); }
  @Post('categories') @RequirePermissions('inventory.create') @AuditAction('RESTAURANT_INVENTORY_CATEGORY_CREATED') category(@Req() r: RequestWithUser, @Body() d: CreateCategoryDto) { return this.service.createCategory(r.tenant!.id, d); }
  @Patch('categories/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_CATEGORY_UPDATED') updateCategory(@Req() r: RequestWithUser, @Param('id') id: string, @Body() d: UpdateCategoryDto) { return this.service.updateCategory(r.tenant!.id, id, d); }
  @Delete('categories/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_CATEGORY_DELETED') deleteCategory(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.deleteCategory(r.tenant!.id, id); }
  @Get('units') @RequirePermissions('inventory.read') units(@Req() r: RequestWithUser, @Query() q: InventoryListQueryDto) { return this.service.units(r.tenant!.id, q); }
  @Post('units') @RequirePermissions('inventory.create') @AuditAction('RESTAURANT_INVENTORY_UNIT_CREATED') unit(@Req() r: RequestWithUser, @Body() d: CreateUnitDto) { return this.service.createUnit(r.tenant!.id, d); }
  @Patch('units/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_UNIT_UPDATED') updateUnit(@Req() r: RequestWithUser, @Param('id') id: string, @Body() d: UpdateUnitDto) { return this.service.updateUnit(r.tenant!.id, id, d); }
  @Delete('units/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_UNIT_DELETED') deleteUnit(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.deleteUnit(r.tenant!.id, id); }
  @Get('warehouses') @RequirePermissions('inventory.read') warehouses(@Req() r: RequestWithUser, @Query() q: InventoryListQueryDto) { return this.service.warehouses(r.tenant!.id, q); }
  @Post('warehouses') @RequirePermissions('inventory.create') @AuditAction('RESTAURANT_INVENTORY_WAREHOUSE_CREATED') warehouse(@Req() r: RequestWithUser, @Body() d: CreateWarehouseDto) { return this.service.createWarehouse(r.tenant!.id, d); }
  @Patch('warehouses/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_WAREHOUSE_UPDATED') updateWarehouse(@Req() r: RequestWithUser, @Param('id') id: string, @Body() d: UpdateWarehouseDto) { return this.service.updateWarehouse(r.tenant!.id, id, d); }
  @Delete('warehouses/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_WAREHOUSE_DELETED') deleteWarehouse(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.deleteWarehouse(r.tenant!.id, id); }
  @Get('suppliers') @RequirePermissions('inventory.read') suppliers(@Req() r: RequestWithUser, @Query() q: InventoryListQueryDto) { return this.service.suppliers(r.tenant!.id, q); }
  @Post('suppliers') @RequirePermissions('inventory.create') @AuditAction('RESTAURANT_INVENTORY_SUPPLIER_CREATED') supplier(@Req() r: RequestWithUser, @Body() d: CreateSupplierDto) { return this.service.createSupplier(r.tenant!.id, d); }
  @Patch('suppliers/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_SUPPLIER_UPDATED') updateSupplier(@Req() r: RequestWithUser, @Param('id') id: string, @Body() d: UpdateSupplierDto) { return this.service.updateSupplier(r.tenant!.id, id, d); }
  @Delete('suppliers/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_SUPPLIER_DELETED') deleteSupplier(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.deleteSupplier(r.tenant!.id, id); }
  @Get('ingredients') @RequirePermissions('inventory.read') ingredients(@Req() r: RequestWithUser, @Query() q: InventoryListQueryDto) { return this.service.ingredients(r.tenant!.id, q); }
  @Post('ingredients') @RequirePermissions('inventory.create') @AuditAction('RESTAURANT_INVENTORY_INGREDIENT_CREATED') ingredient(@Req() r: RequestWithUser, @Body() d: CreateIngredientDto) { return this.service.createIngredient(r.tenant!.id, d); }
  @Patch('ingredients/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_INGREDIENT_UPDATED') updateIngredient(@Req() r: RequestWithUser, @Param('id') id: string, @Body() d: UpdateIngredientDto) { return this.service.updateIngredient(r.tenant!.id, id, d); }
  @Delete('ingredients/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_INGREDIENT_DELETED') deleteIngredient(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.deleteIngredient(r.tenant!.id, id); }
  @Get('branches') @RequirePermissions('inventory.read') branches(@Req() r: RequestWithUser, @Query() q: InventoryListQueryDto) { return this.service.branches(r.tenant!.id, q); }
  @Post('branches') @RequirePermissions('inventory.create') @AuditAction('RESTAURANT_INVENTORY_BRANCH_CREATED') branch(@Req() r: RequestWithUser, @Body() d: CreateBranchDto) { return this.service.createBranch(r.tenant!.id, d); }
  @Patch('branches/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_BRANCH_UPDATED') updateBranch(@Req() r: RequestWithUser, @Param('id') id: string, @Body() d: UpdateBranchDto) { return this.service.updateBranch(r.tenant!.id, id, d); }
  @Delete('branches/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_BRANCH_DELETED') deleteBranch(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.deleteBranch(r.tenant!.id, id); }
  @Get('recipes') @RequirePermissions('inventory.read') recipes(@Req() r: RequestWithUser) { return this.service.recipes(r.tenant!.id); }
  @Post('recipes') @RequirePermissions('inventory.create') recipe(@Req() r: RequestWithUser, @Body() d: CreateRecipeDto) { return this.service.createRecipe(r.tenant!.id, r.user.sub, d); }
  @Patch('recipes/:id/activate') @RequirePermissions('inventory.update') activateRecipe(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.activateRecipe(r.tenant!.id, id); }
  @Patch('recipes/:id/archive') @RequirePermissions('inventory.update') archiveRecipe(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.archiveRecipe(r.tenant!.id, id); }
  @Post('receipts/preview') @RequirePermissions('inventory.create') previewReceipt(@Req() r: RequestWithUser, @Body() d: CreateReceiptDto) { return this.service.previewReceipt(r.tenant!.id, d); }
  @Post('receipts') @RequirePermissions('inventory.create') @AuditAction('RESTAURANT_INVENTORY_RECEIPT_CREATED') receipt(@Req() r: RequestWithUser, @Body() d: CreateReceiptDto) { return this.service.createReceipt(r.tenant!.id, r.user.sub, d); }
  @Patch('receipts/:id') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_RECEIPT_UPDATED') updateReceipt(@Req() r: RequestWithUser, @Param('id') id: string, @Body() d: UpdateReceiptDto) { return this.service.updateReceipt(r.tenant!.id, r.user.sub, id, d); }
  @Get('receipts') @RequirePermissions('inventory.read') receipts(@Req() r: RequestWithUser, @Query('branchId') branchId?: string, @Query('warehouseId') warehouseId?: string, @Query('status') status?: string) { return this.service.receipts(r.tenant!.id, { branchId, warehouseId, status }); }
  @Post('receipts/:id/confirm') @RequirePermissions('inventory.confirm') @AuditAction('RESTAURANT_INVENTORY_RECEIPT_CONFIRMED') confirmReceipt(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.confirmReceipt(r.tenant!.id, r.user.sub, id); }
  @Post('receipts/:id/cancel') @RequirePermissions('inventory.cancel') @AuditAction('RESTAURANT_INVENTORY_RECEIPT_CANCELLED') cancelReceipt(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.cancelReceipt(r.tenant!.id, r.user.sub, id); }
  @Post('consumptions/preview') @RequirePermissions('inventory.read') preview(@Req() r: RequestWithUser, @Body() d: CreateConsumptionDto) { return this.service.previewConsumption(r.tenant!.id, d); }
  @Post('consumptions') @RequirePermissions('inventory.create') consumption(@Req() r: RequestWithUser, @Body() d: CreateConsumptionDto) { return this.service.createConsumption(r.tenant!.id, r.user.sub, d); }
  @Get('consumptions') @RequirePermissions('inventory.read') consumptions(@Req() r: RequestWithUser, @Query('branchId') branchId?: string, @Query('warehouseId') warehouseId?: string, @Query('status') status?: string) { return this.service.consumptions(r.tenant!.id, { branchId, warehouseId, status }); }
  @Post('consumptions/:id/confirm') @RequirePermissions('inventory.confirm') @AuditAction('RESTAURANT_INVENTORY_CONSUMPTION_CONFIRMED') confirmConsumption(@Req() r: RequestWithUser, @Param('id') id: string, @Body() dto: OverrideConfirmationDto) { return this.service.confirmConsumption(r.tenant!.id, r.user.sub, id, (r.user.role === 'SUPERADMIN' && r.user.isGlobalContext) || r.user.permissions.includes('inventory.override'), dto?.justification); }
  @Post('consumptions/:id/cancel') @RequirePermissions('inventory.cancel') cancelConsumption(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.cancelConsumption(r.tenant!.id, r.user.sub, id); }
  @Post('wastes') @RequirePermissions('inventory.create') waste(@Req() r: RequestWithUser, @Body() d: CreateWasteDto) { return this.service.createWaste(r.tenant!.id, r.user.sub, d); }
  @Get('wastes') @RequirePermissions('inventory.read') wastes(@Req() r: RequestWithUser, @Query('branchId') branchId?: string, @Query('warehouseId') warehouseId?: string, @Query('status') status?: string) { return this.service.wastes(r.tenant!.id, { branchId, warehouseId, status }); }
  @Post('wastes/preview') @RequirePermissions('inventory.read') previewWaste(@Req() r: RequestWithUser, @Body() d: CreateWasteDto) { return this.service.previewWaste(r.tenant!.id, d); }
  @Post('wastes/:id/confirm') @RequirePermissions('inventory.confirm') @AuditAction('RESTAURANT_INVENTORY_WASTE_CONFIRMED') confirmWaste(@Req() r: RequestWithUser, @Param('id') id: string, @Body() dto: OverrideConfirmationDto) { return this.service.confirmWaste(r.tenant!.id, r.user.sub, id, (r.user.role === 'SUPERADMIN' && r.user.isGlobalContext) || r.user.permissions.includes('inventory.override'), dto?.justification); }
  @Post('wastes/:id/cancel') @RequirePermissions('inventory.cancel') cancelWaste(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.cancelWaste(r.tenant!.id, r.user.sub, id); }
  @Get('balances') @RequirePermissions('inventory.read') balances(@Req() r: RequestWithUser, @Query('branchId') branchId?: string, @Query('warehouseId') warehouseId?: string) { return this.service.balances(r.tenant!.id, branchId, warehouseId); }
  @Get('movements') @RequirePermissions('inventory.read') movements(@Req() r: RequestWithUser, @Query('ingredientId') ingredientId?: string) { return this.service.movements(r.tenant!.id, ingredientId); }
  @Get('alerts') @RequirePermissions('inventory.report.view') alerts(@Req() r: RequestWithUser) { return this.service.alerts(r.tenant!.id); }
  @Get('lots') @RequirePermissions('inventory.read') lots(@Req() r: RequestWithUser, @Query('status') status?: string) { return this.service.lots(r.tenant!.id, status); }
  @Get('expiry-alerts') @RequirePermissions('inventory.report.view') expiryAlerts(@Req() r: RequestWithUser, @Query('days') days?: string) { return this.service.expiryAlerts(r.tenant!.id, Number(days) || 30); }
  @Post('productions') @RequirePermissions('inventory.create') production(@Req() r: RequestWithUser, @Body() d: CreateProductionDto) { return this.service.createProduction(r.tenant!.id, r.user.sub, d); }
  @Post('productions/preview') @RequirePermissions('inventory.read') previewProduction(@Req() r: RequestWithUser, @Body() d: CreateProductionDto) { return this.service.previewProduction(r.tenant!.id, d); }
  @Get('productions') @RequirePermissions('inventory.read') productions(@Req() r: RequestWithUser, @Query('branchId') branchId?: string, @Query('status') status?: string) { return this.service.productions(r.tenant!.id, { branchId, status }); }
  @Post('productions/:id/confirm') @RequirePermissions('inventory.confirm') @AuditAction('RESTAURANT_INVENTORY_PRODUCTION_CONFIRMED') confirmProduction(@Req() r: RequestWithUser, @Param('id') id: string, @Body() dto: OverrideConfirmationDto) { return this.service.confirmProduction(r.tenant!.id, r.user.sub, id, (r.user.role === 'SUPERADMIN' && r.user.isGlobalContext) || r.user.permissions.includes('inventory.override'), dto?.justification); }
  @Post('productions/:id/cancel') @RequirePermissions('inventory.cancel') cancelProduction(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.cancelProduction(r.tenant!.id, r.user.sub, id); }
  @Post('stock-counts') @RequirePermissions('inventory.create') stockCount(@Req() r: RequestWithUser, @Body() d: CreateStockCountDto) { return this.service.createStockCount(r.tenant!.id, r.user.sub, d); }
  @Get('stock-counts') @RequirePermissions('inventory.read') stockCounts(@Req() r: RequestWithUser, @Query('branchId') branchId?: string, @Query('warehouseId') warehouseId?: string, @Query('status') status?: string) { return this.service.stockCounts(r.tenant!.id, { branchId, warehouseId, status }); }
  @Post('stock-counts/:id/submit') @RequirePermissions('inventory.confirm') @AuditAction('RESTAURANT_INVENTORY_STOCK_COUNT_SUBMITTED') submitStockCount(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.submitStockCount(r.tenant!.id, id); }
  @Post('stock-counts/:id/approve') @RequirePermissions('inventory.confirm') @AuditAction('RESTAURANT_INVENTORY_STOCK_COUNT_APPROVED') approveStockCount(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.approveStockCount(r.tenant!.id, r.user.sub, id); }
  @Post('stock-counts/:id/cancel') @RequirePermissions('inventory.cancel') @AuditAction('RESTAURANT_INVENTORY_STOCK_COUNT_CANCELLED') cancelStockCount(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.cancelStockCount(r.tenant!.id, r.user.sub, id); }
  @Post('transfers') @RequirePermissions('inventory.create') transfer(@Req() r: RequestWithUser, @Body() d: CreateTransferDto) { return this.service.createTransfer(r.tenant!.id, r.user.sub, d); }
  @Get('transfers') @RequirePermissions('inventory.read') transfers(@Req() r: RequestWithUser, @Query('branchId') branchId?: string, @Query('status') status?: string) { return this.service.transfers(r.tenant!.id, { branchId, status }); }
  @Post('transfers/:id/send') @RequirePermissions('inventory.confirm') @AuditAction('RESTAURANT_INVENTORY_TRANSFER_SENT') sendTransfer(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.sendTransfer(r.tenant!.id, r.user.sub, id); }
  @Post('transfers/:id/receive') @RequirePermissions('inventory.confirm') @AuditAction('RESTAURANT_INVENTORY_TRANSFER_RECEIVED') receiveTransfer(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.receiveTransfer(r.tenant!.id, r.user.sub, id); }
  @Post('transfers/:id/cancel') @RequirePermissions('inventory.cancel') @AuditAction('RESTAURANT_INVENTORY_TRANSFER_CANCELLED') cancelTransfer(@Req() r: RequestWithUser, @Param('id') id: string) { return this.service.cancelTransfer(r.tenant!.id, r.user.sub, id); }
  @Post('adjustments') @RequirePermissions('inventory.update') @AuditAction('RESTAURANT_INVENTORY_ADJUSTMENT_CREATED') adjustment(@Req() r: RequestWithUser, @Body() d: CreateAdjustmentDto) { return this.service.createAdjustment(r.tenant!.id, r.user.sub, d); }
}
