ALTER TYPE "AutomationTriggerEvent" ADD VALUE IF NOT EXISTS 'APPLICATION_STAGE_CHANGED';
ALTER TYPE "AutomationTriggerEvent" ADD VALUE IF NOT EXISTS 'APPLICATION_REJECTED';
ALTER TYPE "AutomationTriggerEvent" ADD VALUE IF NOT EXISTS 'INTERVIEW_SCHEDULED';
ALTER TYPE "AutomationTriggerEvent" ADD VALUE IF NOT EXISTS 'INTERVIEW_COMPLETED';
