CREATE TABLE "InventorySupplier" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT, "phone" TEXT, "taxId" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "InventorySupplier_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "InventorySupplier_tenantId_name_key" ON "InventorySupplier"("tenantId", "name");
CREATE INDEX "InventorySupplier_tenantId_isActive_idx" ON "InventorySupplier"("tenantId", "isActive");
CREATE TABLE "InventoryPurchaseOrder" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "branchId" TEXT NOT NULL, "supplierId" TEXT NOT NULL, "code" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'DRAFT', "currency" TEXT NOT NULL DEFAULT 'USD', "budgetAmount" DECIMAL(14,2), "totalAmount" DECIMAL(14,2) NOT NULL DEFAULT 0, "notes" TEXT, "requestedById" TEXT NOT NULL, "approvedById" TEXT, "approvedAt" TIMESTAMP(3), "receivedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "InventoryPurchaseOrder_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "InventoryPurchaseOrder_tenantId_code_key" ON "InventoryPurchaseOrder"("tenantId", "code");
CREATE INDEX "InventoryPurchaseOrder_tenantId_branchId_status_idx" ON "InventoryPurchaseOrder"("tenantId", "branchId", "status");
CREATE TABLE "InventoryPurchaseOrderLine" ("id" TEXT NOT NULL, "purchaseOrderId" TEXT NOT NULL, "itemId" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "receivedQty" INTEGER NOT NULL DEFAULT 0, "unitCost" DECIMAL(14,2) NOT NULL, CONSTRAINT "InventoryPurchaseOrderLine_pkey" PRIMARY KEY ("id"));
CREATE INDEX "InventoryPurchaseOrderLine_purchaseOrderId_idx" ON "InventoryPurchaseOrderLine"("purchaseOrderId");
ALTER TABLE "InventoryPurchaseOrderLine" ADD CONSTRAINT "InventoryPurchaseOrderLine_purchaseOrderId_fkey" FOREIGN KEY ("purchaseOrderId") REFERENCES "InventoryPurchaseOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
