import { Injectable } from '@nestjs/common';
import { DOMAIN_EVENT_NAMES, DomainEventName } from './domain-event.constants';
import { MESSAGE_QUEUE_NAMES, MessageQueueName } from '../messaging/messaging.constants';

@Injectable()
export class DomainEventRoutingService {
  private readonly queueByEvent: Record<DomainEventName, MessageQueueName> = {
    [DOMAIN_EVENT_NAMES.CANDIDATE_HIRED]: MESSAGE_QUEUE_NAMES.AUTOMATION_EVENTS,
    [DOMAIN_EVENT_NAMES.EMPLOYEE_BRANCH_CHANGED]: MESSAGE_QUEUE_NAMES.WORKFLOW_EVENTS,
    [DOMAIN_EVENT_NAMES.EMPLOYEE_OFFBOARDING_STARTED]: MESSAGE_QUEUE_NAMES.WORKFLOW_EVENTS,
    [DOMAIN_EVENT_NAMES.ONBOARDING_COMPLETED]: MESSAGE_QUEUE_NAMES.WORKFLOW_EVENTS,
    [DOMAIN_EVENT_NAMES.INVENTORY_ASSET_ASSIGNED]: MESSAGE_QUEUE_NAMES.WORKFLOW_EVENTS,
    [DOMAIN_EVENT_NAMES.TRAINING_COMPLETED]: MESSAGE_QUEUE_NAMES.TRAINING,
    [DOMAIN_EVENT_NAMES.OPERATION_HANDOFF_COMPLETED]: MESSAGE_QUEUE_NAMES.WORKFLOW_EVENTS,
    [DOMAIN_EVENT_NAMES.COMPLIANCE_CLOSED]: MESSAGE_QUEUE_NAMES.WORKFLOW_EVENTS,
  };

  resolveQueue(eventName: DomainEventName) {
    return this.queueByEvent[eventName];
  }
}
