export const en = {
  common: {
    unexpected_error: 'An unexpected error occurred.',
    validation_error: 'Review the submitted data.',
    unauthorized: 'Your session is not valid.',
    forbidden: 'You do not have permission to perform this action.',
    not_found: 'The requested resource was not found.',
  },
  vacancies: {
    public_title: 'Available jobs',
    private_access_required: 'This job requires authorized access.',
  },
  applications: {
    submitted: 'Your application was submitted successfully.',
    already_submitted: 'An application already exists for this job.',
  },
  dashboard: {
    review_application: 'Review new application',
    prepare_interview: 'Prepare interview',
  },
  applications_ats: {
    no_undoable_transition: "There's no move of your own that can be undone",
    previous_stage_gone: 'The previous stage is no longer available',
  },
  hiring_progress: {
    docs_missing_one: '1 required document is missing.',
    docs_missing_many: '{{count}} required documents are missing.',
    signatures_pending: 'There are signature requests pending.',
    waiting_candidate: 'The hire is waiting for the candidate to answer.',
    offer_not_configured: 'Set up an offer before sending it.',
    activity_create: 'The hire was created.',
    activity_send_offer: 'The offer was sent to the candidate.',
    activity_accept_offer: 'The candidate accepted the offer.',
    activity_reject_offer: 'The candidate turned down the offer.',
    activity_confirm: 'The hire was confirmed.',
    activity_cancel: 'The hire was cancelled.',
    activity_update: 'The hire was updated.',
  },
  scope: {
    tenant_out_of_scope: 'Company outside the authorized scope',
    branch_out_of_scope: 'Branch outside the authorized scope',
    branch_not_found: 'Branch not found',
    vacancy_not_found: 'Vacancy not found',
    recruiter_not_found: 'Recruiter not found',
    invalid_date_range: 'The start date must be earlier than the end date',
    period_too_long: 'The maximum allowed period is 366 days',
  },
  ats_analytics: {
    source: 'Applications, stage audit trail, interviews and persisted offers',
    source_unattributed: 'Not reported',
    no_structured_reason: 'No structured reason',
    csv_summary: 'Summary',
    csv_applications: 'Applications',
    csv_unique_candidates: 'Unique candidates',
    csv_hires: 'Hires',
    csv_conversion: 'Conversion',
    csv_time_to_hire: 'Average time to hire',
    csv_hours: 'hours',
    csv_sla_compliance: 'SLA compliance',
    csv_funnel: 'Funnel',
    csv_source: 'Source',
    csv_quality_of_hire: 'Quality of hire',
    csv_days: 'days',
    csv_retention: 'retention',
    csv_vacancy: 'Vacancy',
    csv_recruiter: 'Recruiter',
    csv_rejection: 'Rejection',
    csv_dimension: 'Dimension',
    csv_indicator: 'Indicator',
    csv_value: 'Value',
    csv_detail: 'Detail',
    csv_filename: 'ats-analytics',
    insight_bottleneck_title: 'Longest dwell time: {{stage}}',
    insight_bottleneck_detail: 'Average of {{hours}} hours in the stage.',
    insight_dropoff_title: 'High drop-off at {{stage}}',
    insight_dropoff_detail: '{{rate}}% do not continue from the previous stage.',
    insight_source_title: 'Incomplete candidate source data',
    insight_source_detail: '{{rate}}% of applications have no attributed source.',
    insight_sla_title: 'Applications breaching SLA',
    insight_sla_detail: '{{count}} applications need attention.',
    insight_noshow_title: 'Interview no-shows',
    insight_noshow_detail: 'The no-show rate is {{rate}}%.',
    insight_offer_title: 'Offer acceptance below target',
    insight_offer_detail: 'Current acceptance is {{rate}}%.',
  },
  applications_public: {
    referral_vacancy_unavailable: 'This vacancy is not available for referrals.',
    could_not_validate: 'The application could not be validated',
    slow_down: 'Take your time completing the application and try again',
    too_many_attempts: 'You have made too many attempts. Wait a moment and try again.',
    evidence_disclaimer: 'Operational file for internal review, audit and legal advice. Check local requirements on retention, privacy and evidentiary admissibility.',
    modified_elsewhere: 'The application was modified by someone else. Refresh the view before continuing.',
    resume_upload_unavailable: 'Résumé upload is not available',
    candidate_profile_not_found: 'The candidate profile was not found',
  },
  talent_crm: {
    suppressed_unsubscribed: 'The candidate unsubscribed from email communications.',
    suggestion_reason: 'Profile with prior experience available for review.',
    campaign_needs_review: 'The campaign requires a reviewed audience and two approvals from different users.',
    audience_reviewed: 'The audience has been reviewed. Email delivery requires a separate send authorization.',
    audience_not_recomputable: 'The audience cannot be recalculated for this campaign.',
    suppressed_do_not_contact: 'The candidate asked not to be contacted.',
    suppressed_no_consent: 'There is no consent for email campaigns.',
    suppressed_no_application: 'There is no accessible application to link the email to.',
    confirm_audience: 'You must confirm the audience before enabling delivery.',
    prepare_audience_first: 'Prepare the campaign audience first.',
    audience_changed: 'The audience changed. Review it again before sending.',
    review_audience_first: 'Review the campaign audience first.',
    step_count_mismatch: 'The number of steps does not match the sequence',
    signal_same_email: 'Identical email',
    signal_same_phone: 'Identical phone',
    signal_same_linkedin: 'Identical LinkedIn',
    signal_same_resume: 'Identical résumé',
    signal_same_name: 'Identical name',
    signal_same_city: 'Identical city',
  },
  application_sla: {
    escalated_title: 'Recruitment SLA breached',
    escalated_detail: '{{candidate}} exceeded the SLA for the {{stage}} stage.',
    warning_title: 'SLA about to expire',
    warning_detail: 'The {{stage}} stage for {{candidate}} is due on {{dueAt}}.',
    reassigned_title: 'Application reassigned due to SLA',
    reassigned_detail: '{{candidate}} was automatically reassigned because the SLA expired.',
  },
  offer_pdf: {
    filename: 'job-offer',
    title: 'Job offer',
    candidate: 'Candidate',
    position: 'Position',
    compensation: 'Compensation',
    start_date: 'Start date',
    valid_until: 'Valid until',
    benefits: 'Benefits',
    none_specified: 'Not specified',
    language_es: 'Spanish',
    language_en: 'English',
    translation_notice: 'Courtesy translation. The prevailing copy, and the one signed electronically, is the one drafted in {{language}}.',
  },
  offers: {
    email_default_message: 'We have prepared a job offer for you.',
    email_review_and_sign: 'Review and sign your offer: {{url}}',
    application_must_be_approved: 'The application must be approved before creating an offer',
    already_active: 'This application already has an active offer',
    no_more_versions: 'This offer no longer accepts new versions',
    not_pending_approval: 'The offer is not pending approval',
    approval_not_found: 'Approval not found',
    approval_other_user: 'The approval is assigned to another user',
    only_company_admins: 'Only company administrators can create offers',
    needs_both_approvals: 'The offer requires both approvals before it can be sent',
    validity_already_ended: 'The offer validity period has already ended',
    accepted_cannot_cancel: 'An accepted offer cannot be cancelled',
    no_signature_request: 'The offer has no associated signature request',
    acceptance_needs_consent: 'Acceptance requires consent and the candidate\'s full name',
    acceptance_needs_signature: 'Acceptance must be completed through the associated electronic signature',
    conversion_failed: 'The automatic conversion could not be started',
    not_accepted_yet: 'The offer has not been accepted yet',
    signature_incomplete: 'The electronic signature is not complete yet',
    not_found: 'Offer not found',
    application_not_found: 'Application not found',
    branch_out_of_scope: 'The branch is outside the user\'s scope',
    invalid_dates: 'The offer dates are not valid',
    validity_must_be_future: 'The validity period must end in the future',
    current_version_not_found: 'Current offer version not found',
    version_not_found: 'Offer version not found',
    not_available_to_respond: 'The offer is not available for a response',
    expired: 'The offer has expired',
  },
  ats_comms: {
    application_confirmation_subject: 'We received your application for {{vacancyTitle}}',
    application_confirmation_body: 'Hi {{candidateName}}, we received your application. We will let you know as the process moves along.',
    stage_update_subject: 'An update on your application for {{vacancyTitle}}',
    stage_update_body: 'Hi {{candidateName}}, your application moved to the {{stageName}} stage.',
    rejection_subject: 'An update about your application for {{vacancyTitle}}',
    rejection_body: 'Hi {{candidateName}}, thank you for your interest. This time the process will not continue. Reason: {{reason}}.',
    interview_scheduled_subject: 'Interview scheduled for {{vacancyTitle}}',
    interview_scheduled_body: 'Hi {{candidateName}}, your interview is scheduled for {{interviewDate}}. {{interviewLocation}}',
    interview_reminder_subject: 'Interview reminder for {{vacancyTitle}}',
    interview_reminder_body: 'Hi {{candidateName}}, a reminder about your interview on {{interviewDate}}. {{interviewLocation}}',
    interview_rescheduled_subject: 'Interview rescheduled for {{vacancyTitle}}',
    interview_rescheduled_body: 'Hi {{candidateName}}, the interview for {{vacancyTitle}} was moved to {{interviewDate}}.',
    interview_cancelled_subject: 'Interview cancelled for {{vacancyTitle}}',
    interview_cancelled_body: 'Hi {{candidateName}}, the interview set for {{interviewDate}} was cancelled.',
    offer_subject: 'Offer for {{vacancyTitle}}',
    offer_body: 'Hi {{candidateName}}, we are glad to tell you your process moved to an offer. {{offerMessage}}',
    approval_subject: 'Approval needed: {{candidateName}}',
    approval_body: "{{candidateName}}'s application for {{vacancyTitle}} is asking to move to {{stageName}}.",
    generic_subject: 'A message about {{vacancyTitle}}',
    generic_body: 'Hi {{candidateName}}, {{message}}',
    category_disabled: 'The candidate turned off this category of messages',
    email_channel_disabled: 'The user turned off the email channel',
  },
  notifications: {
    candidate_hired: { title: 'Hiring confirmed', message: 'Hiring was confirmed and onboarding has started.' },
    application_stage_changed: { title: 'Application stage updated', message: 'An application changed stage in the pipeline.' },
    application_rejected: { title: 'Application rejected', message: 'An application was rejected in the selection process.' },
    interview_scheduled: { title: 'Interview scheduled', message: 'An interview was scheduled for an application.' },
    interview_completed: { title: 'Interview completed', message: 'An interview is ready for evaluation.' },
    branch_changed: { title: 'Branch changed', message: 'The assigned branch was updated and related tasks are being recalculated.' },
    offboarding_started: { title: 'Offboarding started', message: 'Access closure and asset recovery are being tracked.' },
    onboarding_completed: { title: 'Onboarding completed', message: 'All required onboarding tasks were completed.' },
    asset_assigned: { title: 'Asset assigned', message: 'A new inventory assignment was recorded.' },
    training_completed: { title: 'Training completed', message: 'The training activity was completed successfully.' },
    handoff_completed: { title: 'Operational handoff completed', message: 'The operational handoff was confirmed.' },
    compliance_closed: { title: 'Compliance control closed', message: 'The required control was closed with traceability.' },
  },
} as const;
