export const en = {
  common: {
    unexpected_error: 'An unexpected error occurred.',
    validation_error: 'Review the submitted data.',
    unauthorized: 'Your session is not valid.',
    forbidden: 'You do not have permission to perform this action.',
    not_found: 'The requested resource was not found.',
  },
  vacancies: {
    public_title: 'Available jobs',
    private_access_required: 'This job requires authorized access.',
  },
  applications: {
    submitted: 'Your application was submitted successfully.',
    already_submitted: 'An application already exists for this job.',
  },
  dashboard: {
    review_application: 'Review new application',
    prepare_interview: 'Prepare interview',
  },
  applications_ats: {
    no_undoable_transition: "There's no move of your own that can be undone",
    previous_stage_gone: 'The previous stage is no longer available',
  },
  hiring_progress: {
    docs_missing_one: '1 required document is missing.',
    docs_missing_many: '{{count}} required documents are missing.',
    signatures_pending: 'There are signature requests pending.',
    waiting_candidate: 'The hire is waiting for the candidate to answer.',
    offer_not_configured: 'Set up an offer before sending it.',
    activity_create: 'The hire was created.',
    activity_send_offer: 'The offer was sent to the candidate.',
    activity_accept_offer: 'The candidate accepted the offer.',
    activity_reject_offer: 'The candidate turned down the offer.',
    activity_confirm: 'The hire was confirmed.',
    activity_cancel: 'The hire was cancelled.',
    activity_update: 'The hire was updated.',
  },
  notifications: {
    candidate_hired: { title: 'Hiring confirmed', message: 'Hiring was confirmed and onboarding has started.' },
    application_stage_changed: { title: 'Application stage updated', message: 'An application changed stage in the pipeline.' },
    application_rejected: { title: 'Application rejected', message: 'An application was rejected in the selection process.' },
    interview_scheduled: { title: 'Interview scheduled', message: 'An interview was scheduled for an application.' },
    interview_completed: { title: 'Interview completed', message: 'An interview is ready for evaluation.' },
    branch_changed: { title: 'Branch changed', message: 'The assigned branch was updated and related tasks are being recalculated.' },
    offboarding_started: { title: 'Offboarding started', message: 'Access closure and asset recovery are being tracked.' },
    onboarding_completed: { title: 'Onboarding completed', message: 'All required onboarding tasks were completed.' },
    asset_assigned: { title: 'Asset assigned', message: 'A new inventory assignment was recorded.' },
    training_completed: { title: 'Training completed', message: 'The training activity was completed successfully.' },
    handoff_completed: { title: 'Operational handoff completed', message: 'The operational handoff was confirmed.' },
    compliance_closed: { title: 'Compliance control closed', message: 'The required control was closed with traceability.' },
  },
} as const;
