export const es = {
  common: {
    unexpected_error: 'Ocurrió un error inesperado.',
    validation_error: 'Revisa los datos enviados.',
    unauthorized: 'Tu sesión no es válida.',
    forbidden: 'No tienes permisos para realizar esta acción.',
    not_found: 'No se encontró el recurso solicitado.',
  },
  vacancies: {
    public_title: 'Vacantes disponibles',
    private_access_required: 'Esta vacante requiere acceso autorizado.',
  },
  applications: {
    submitted: 'Tu postulación fue enviada correctamente.',
    already_submitted: 'Ya existe una postulación para esta vacante.',
  },
  dashboard: {
    review_application: 'Revisar nueva postulación',
    prepare_interview: 'Preparar entrevista',
  },
  applications_ats: {
    no_undoable_transition: 'No hay una transición propia que se pueda deshacer',
    previous_stage_gone: 'La etapa anterior ya no está disponible',
  },
  hiring_progress: {
    docs_missing_one: 'Falta 1 documento obligatorio.',
    docs_missing_many: 'Faltan {{count}} documentos obligatorios.',
    signatures_pending: 'Hay solicitudes de firma pendientes.',
    waiting_candidate: 'La contratación está esperando una respuesta del candidato.',
    offer_not_configured: 'Configura una oferta antes de enviarla.',
    activity_create: 'Se creó la contratación.',
    activity_send_offer: 'Se envió la oferta al candidato.',
    activity_accept_offer: 'El candidato aceptó la oferta.',
    activity_reject_offer: 'El candidato rechazó la oferta.',
    activity_confirm: 'Se confirmó la contratación.',
    activity_cancel: 'Se canceló la contratación.',
    activity_update: 'Se actualizó la contratación.',
  },
  scope: {
    tenant_out_of_scope: 'Empresa fuera del alcance autorizado',
    branch_out_of_scope: 'Sucursal fuera del alcance autorizado',
    branch_not_found: 'Sucursal no encontrada',
    vacancy_not_found: 'Vacante no encontrada',
    recruiter_not_found: 'Reclutador no encontrado',
    invalid_date_range: 'La fecha inicial debe ser anterior a la fecha final',
    period_too_long: 'El periodo máximo permitido es de 366 días',
  },
  ats_analytics: {
    source: 'Postulaciones, auditoría de etapas, entrevistas y ofertas persistentes',
    source_unattributed: 'No informado',
    no_structured_reason: 'Sin motivo estructurado',
    csv_summary: 'Resumen',
    csv_applications: 'Postulaciones',
    csv_unique_candidates: 'Candidatos únicos',
    csv_hires: 'Contrataciones',
    csv_conversion: 'Conversión',
    csv_time_to_hire: 'Tiempo promedio de contratación',
    csv_hours: 'horas',
    csv_sla_compliance: 'Cumplimiento SLA',
    csv_funnel: 'Embudo',
    csv_source: 'Fuente',
    csv_quality_of_hire: 'Calidad de contratación',
    csv_days: 'días',
    csv_retention: 'retención',
    csv_vacancy: 'Vacante',
    csv_recruiter: 'Reclutador',
    csv_rejection: 'Descarte',
    csv_dimension: 'Dimensión',
    csv_indicator: 'Indicador',
    csv_value: 'Valor',
    csv_detail: 'Detalle',
    csv_filename: 'analitica-ats',
    insight_bottleneck_title: 'Mayor permanencia: {{stage}}',
    insight_bottleneck_detail: 'Promedio de {{hours}} horas en la etapa.',
    insight_dropoff_title: 'Pérdida elevada en {{stage}}',
    insight_dropoff_detail: '{{rate}}% no continúa desde la etapa anterior.',
    insight_source_title: 'Origen de candidatos incompleto',
    insight_source_detail: '{{rate}}% de las postulaciones no tiene fuente atribuida.',
    insight_sla_title: 'Postulaciones fuera de SLA',
    insight_sla_detail: '{{count}} postulaciones requieren atención.',
    insight_noshow_title: 'Ausencias en entrevistas',
    insight_noshow_detail: 'La tasa de ausencia es {{rate}}%.',
    insight_offer_title: 'Aceptación de ofertas por debajo del objetivo',
    insight_offer_detail: 'La aceptación actual es {{rate}}%.',
  },
  applications_public: {
    referral_vacancy_unavailable: 'Vacante no disponible para referidos.',
    could_not_validate: 'No fue posible validar la postulación',
    slow_down: 'Completa la postulación con calma e inténtalo nuevamente',
    too_many_attempts: 'Has realizado demasiados intentos. Espera un momento y vuelve a intentarlo.',
    evidence_disclaimer: 'Expediente operativo para revisión interna, auditoría y asesoría legal. Verifique requisitos locales de retención, privacidad y admisibilidad probatoria.',
    modified_elsewhere: 'La postulación fue modificada por otra persona. Actualiza la vista antes de continuar.',
    resume_upload_unavailable: 'La carga de currículums no está disponible',
    candidate_profile_not_found: 'No se encontró el perfil del candidato',
  },
  talent_crm: {
    suppressed_unsubscribed: 'El candidato se dio de baja de comunicaciones por correo.',
    suggestion_reason: 'Perfil con experiencia previa disponible para revisión.',
    campaign_needs_review: 'La campaña requiere audiencia revisada y dos aprobaciones de usuarios distintos.',
    audience_reviewed: 'La audiencia fue revisada. La entrega de correo requiere una autorización de envío independiente.',
    audience_not_recomputable: 'La audiencia no se puede recalcular para esta campaña.',
    suppressed_do_not_contact: 'El candidato solicitó no recibir contacto.',
    suppressed_no_consent: 'No existe consentimiento para campañas por correo.',
    suppressed_no_application: 'No tiene una postulación accesible para asociar el correo.',
    confirm_audience: 'Debes confirmar la audiencia antes de habilitar el envío.',
    prepare_audience_first: 'Primero prepara la audiencia de la campaña.',
    audience_changed: 'La audiencia cambió. Vuelve a revisarla antes de enviar.',
    review_audience_first: 'Primero revisa la audiencia de la campaña.',
    step_count_mismatch: 'El número de pasos no coincide con la secuencia',
    signal_same_email: 'Correo idéntico',
    signal_same_phone: 'Teléfono idéntico',
    signal_same_linkedin: 'LinkedIn idéntico',
    signal_same_resume: 'CV idéntico',
    signal_same_name: 'Nombre idéntico',
    signal_same_city: 'Ciudad idéntica',
  },
  application_sla: {
    escalated_title: 'SLA de reclutamiento vencido',
    escalated_detail: '{{candidate}} superó el SLA de la etapa {{stage}}.',
    warning_title: 'SLA próximo a vencer',
    warning_detail: 'La etapa {{stage}} de {{candidate}} vence el {{dueAt}}.',
    reassigned_title: 'Postulación reasignada por SLA',
    reassigned_detail: '{{candidate}} fue reasignado automáticamente por vencimiento de SLA.',
  },
  offer_pdf: {
    filename: 'oferta',
    title: 'Oferta laboral',
    candidate: 'Candidato',
    position: 'Puesto',
    compensation: 'Compensacion',
    start_date: 'Fecha de ingreso',
    valid_until: 'Vigencia',
    benefits: 'Beneficios',
    none_specified: 'No especificados',
    language_es: 'castellano',
    language_en: 'ingles',
    translation_notice: 'Traduccion de cortesia. El ejemplar que prevalece y que se firmo electronicamente es el redactado en {{language}}.',
  },
  offers: {
    email_default_message: 'Hemos preparado una oferta laboral para ti.',
    email_review_and_sign: 'Revisa y firma tu oferta: {{url}}',
    application_must_be_approved: 'La postulación debe estar aprobada antes de crear una oferta',
    already_active: 'La postulación ya tiene una oferta activa',
    no_more_versions: 'La oferta ya no admite nuevas versiones',
    not_pending_approval: 'La oferta no está pendiente de aprobación',
    approval_not_found: 'Aprobación no encontrada',
    approval_other_user: 'La aprobación está asignada a otro usuario',
    only_company_admins: 'Solo los usuarios administradores de la empresa pueden crear ofertas',
    needs_both_approvals: 'La oferta requiere ambas aprobaciones antes de enviarse',
    validity_already_ended: 'La vigencia de la oferta ya terminó',
    accepted_cannot_cancel: 'Una oferta aceptada no puede cancelarse',
    no_signature_request: 'La oferta no tiene una solicitud de firma asociada',
    acceptance_needs_consent: 'La aceptación requiere consentimiento y el nombre completo del candidato',
    acceptance_needs_signature: 'La aceptación debe completarse mediante la firma electrónica asociada',
    conversion_failed: 'No fue posible iniciar la conversión automática',
    not_accepted_yet: 'La oferta todavía no fue aceptada',
    signature_incomplete: 'La firma electrónica todavía no está completa',
    not_found: 'Oferta no encontrada',
    application_not_found: 'Postulación no encontrada',
    branch_out_of_scope: 'La sucursal está fuera del alcance del usuario',
    invalid_dates: 'Las fechas de la oferta no son válidas',
    validity_must_be_future: 'La vigencia debe terminar en el futuro',
    current_version_not_found: 'Versión vigente de la oferta no encontrada',
    version_not_found: 'Versión de oferta no encontrada',
    not_available_to_respond: 'La oferta no está disponible para responder',
    expired: 'La oferta venció',
  },
  ats_comms: {
    application_confirmation_subject: 'Recibimos tu postulación para {{vacancyTitle}}',
    application_confirmation_body: 'Hola {{candidateName}}, recibimos correctamente tu postulación. Te informaremos cuando avance el proceso.',
    stage_update_subject: 'Actualización de tu proceso para {{vacancyTitle}}',
    stage_update_body: 'Hola {{candidateName}}, tu postulación avanzó a la etapa {{stageName}}.',
    rejection_subject: 'Actualización sobre tu postulación para {{vacancyTitle}}',
    rejection_body: 'Hola {{candidateName}}, agradecemos tu interés. En esta ocasión el proceso no continuará. Motivo: {{reason}}.',
    interview_scheduled_subject: 'Entrevista programada para {{vacancyTitle}}',
    interview_scheduled_body: 'Hola {{candidateName}}, tu entrevista fue programada para {{interviewDate}}. {{interviewLocation}}',
    interview_reminder_subject: 'Recordatorio de entrevista para {{vacancyTitle}}',
    interview_reminder_body: 'Hola {{candidateName}}, te recordamos tu entrevista el {{interviewDate}}. {{interviewLocation}}',
    interview_rescheduled_subject: 'Entrevista reprogramada para {{vacancyTitle}}',
    interview_rescheduled_body: 'Hola {{candidateName}}, la entrevista para {{vacancyTitle}} fue reprogramada para {{interviewDate}}.',
    interview_cancelled_subject: 'Entrevista cancelada para {{vacancyTitle}}',
    interview_cancelled_body: 'Hola {{candidateName}}, la entrevista prevista para {{interviewDate}} fue cancelada.',
    offer_subject: 'Oferta para {{vacancyTitle}}',
    offer_body: 'Hola {{candidateName}}, queremos comunicarte que tu proceso avanzó a oferta. {{offerMessage}}',
    approval_subject: 'Aprobación requerida: {{candidateName}}',
    approval_body: 'La postulación de {{candidateName}} para {{vacancyTitle}} solicita avanzar a {{stageName}}.',
    generic_subject: 'Mensaje sobre {{vacancyTitle}}',
    generic_body: 'Hola {{candidateName}}, {{message}}',
    category_disabled: 'El candidato desactivó esta categoría de comunicaciones',
    email_channel_disabled: 'El canal de correo fue desactivado por el usuario',
  },
  notifications: {
    candidate_hired: { title: 'Contratación confirmada', message: 'La contratación fue confirmada y el flujo de incorporación comenzó.' },
    application_stage_changed: { title: 'Etapa de candidatura actualizada', message: 'Una candidatura cambió de etapa en el pipeline.' },
    application_rejected: { title: 'Candidatura descartada', message: 'Se registró un descarte en el proceso de selección.' },
    interview_scheduled: { title: 'Entrevista programada', message: 'Se agendó una entrevista para una candidatura.' },
    interview_completed: { title: 'Entrevista completada', message: 'Una entrevista está lista para evaluación.' },
    branch_changed: { title: 'Cambio de sucursal', message: 'Se actualizó la sucursal asignada y se están recalculando las tareas relacionadas.' },
    offboarding_started: { title: 'Proceso de salida iniciado', message: 'El cierre de accesos y la recuperación de activos quedaron en seguimiento.' },
    onboarding_completed: { title: 'Incorporación completada', message: 'Todas las tareas obligatorias de incorporación fueron completadas.' },
    asset_assigned: { title: 'Activo asignado', message: 'Se registró una nueva asignación de inventario.' },
    training_completed: { title: 'Capacitación completada', message: 'La actividad formativa fue completada correctamente.' },
    handoff_completed: { title: 'Entrega operativa completada', message: 'La transferencia operativa fue confirmada.' },
    compliance_closed: { title: 'Control de cumplimiento cerrado', message: 'El control obligatorio fue cerrado con trazabilidad.' },
  },
} as const;
