export const es = {
  common: {
    unexpected_error: 'Ocurrió un error inesperado.',
    validation_error: 'Revisa los datos enviados.',
    unauthorized: 'Tu sesión no es válida.',
    forbidden: 'No tienes permisos para realizar esta acción.',
    not_found: 'No se encontró el recurso solicitado.',
  },
  vacancies: {
    public_title: 'Vacantes disponibles',
    private_access_required: 'Esta vacante requiere acceso autorizado.',
  },
  applications: {
    submitted: 'Tu postulación fue enviada correctamente.',
    already_submitted: 'Ya existe una postulación para esta vacante.',
  },
  dashboard: {
    review_application: 'Revisar nueva postulación',
    prepare_interview: 'Preparar entrevista',
  },
  applications_ats: {
    no_undoable_transition: 'No hay una transición propia que se pueda deshacer',
    previous_stage_gone: 'La etapa anterior ya no está disponible',
  },
  hiring_progress: {
    docs_missing_one: 'Falta 1 documento obligatorio.',
    docs_missing_many: 'Faltan {{count}} documentos obligatorios.',
    signatures_pending: 'Hay solicitudes de firma pendientes.',
    waiting_candidate: 'La contratación está esperando una respuesta del candidato.',
    offer_not_configured: 'Configura una oferta antes de enviarla.',
    activity_create: 'Se creó la contratación.',
    activity_send_offer: 'Se envió la oferta al candidato.',
    activity_accept_offer: 'El candidato aceptó la oferta.',
    activity_reject_offer: 'El candidato rechazó la oferta.',
    activity_confirm: 'Se confirmó la contratación.',
    activity_cancel: 'Se canceló la contratación.',
    activity_update: 'Se actualizó la contratación.',
  },
  notifications: {
    candidate_hired: { title: 'Contratación confirmada', message: 'La contratación fue confirmada y el flujo de incorporación comenzó.' },
    application_stage_changed: { title: 'Etapa de candidatura actualizada', message: 'Una candidatura cambió de etapa en el pipeline.' },
    application_rejected: { title: 'Candidatura descartada', message: 'Se registró un descarte en el proceso de selección.' },
    interview_scheduled: { title: 'Entrevista programada', message: 'Se agendó una entrevista para una candidatura.' },
    interview_completed: { title: 'Entrevista completada', message: 'Una entrevista está lista para evaluación.' },
    branch_changed: { title: 'Cambio de sucursal', message: 'Se actualizó la sucursal asignada y se están recalculando las tareas relacionadas.' },
    offboarding_started: { title: 'Proceso de salida iniciado', message: 'El cierre de accesos y la recuperación de activos quedaron en seguimiento.' },
    onboarding_completed: { title: 'Incorporación completada', message: 'Todas las tareas obligatorias de incorporación fueron completadas.' },
    asset_assigned: { title: 'Activo asignado', message: 'Se registró una nueva asignación de inventario.' },
    training_completed: { title: 'Capacitación completada', message: 'La actividad formativa fue completada correctamente.' },
    handoff_completed: { title: 'Entrega operativa completada', message: 'La transferencia operativa fue confirmada.' },
    compliance_closed: { title: 'Control de cumplimiento cerrado', message: 'El control obligatorio fue cerrado con trazabilidad.' },
  },
} as const;
